// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grocery.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getGroceryLists = `-- name: GetGroceryLists :many
SELECT list_id as id,
       name,
       created_at,
       updated_at
FROM pantrywise.pantry.grocery_lists
WHERE household_id = $1
`

type GetGroceryListsRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) GetGroceryLists(ctx context.Context, householdID uuid.UUID) ([]GetGroceryListsRow, error) {
	rows, err := q.db.Query(ctx, getGroceryLists, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroceryListsRow
	for rows.Next() {
		var i GetGroceryListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
