// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PantryFood struct {
	FoodID      uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PantryGroceryItem struct {
	ItemID       uuid.UUID
	ListID       uuid.UUID
	FoodID       uuid.UUID
	StoreID      *uuid.UUID
	Quantity     pgtype.Numeric
	Unit         string
	PurchaseDate pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type PantryGroceryList struct {
	ListID      uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PantryHousehold struct {
	HouseholdID uuid.UUID
	Name        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PantryRecipe struct {
	RecipeID    uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	CategoryID  *uuid.UUID
	PlannedDate pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PantryRecipeCategory struct {
	CategoryID  uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	ColorRgba   int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PantryRecipeIngredient struct {
	IngredientID uuid.UUID
	RecipeID     uuid.UUID
	FoodID       uuid.UUID
	Quantity     pgtype.Numeric
	Unit         string
	Preparation  pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type PantryStore struct {
	StoreID     uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PantryStoreListing struct {
	ListingID  uuid.UUID
	StoreID    uuid.UUID
	FoodID     uuid.UUID
	PriceCents int32
	Quantity   int32
	Unit       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
